module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        serif: ['Playfair Display', 'serif'],
      },
      spacing: {
        '1': '1px',
        '3': '3px',
        '5': '5px',
        '8': '8px',
        '9': '9px',
        '12': '12px',
        '10': '10px',
        '14': '14px',
        '13': '13px',
        '16': '16px',
        '18': '18px',
        '20': '20px',
        '21': '21px',
        '22': '22px',
        '24': '24px',
        '27': '27px',
        '30': '30px',
        '32': '32px',
        '35': '35px',
        '37': '37px',
        '40': '40px',
        '42': '42px',
        '48': '48px',
        '50': '50px',
        '56': '56px',
        '60': '60px',
        '64': '64px',
        '66': '66px',
        '72': '72px',
        '76': '76px',
        '80': '80px',
        '87': '87px',
        '96': '96px',
        '102': '102px',
        '110': '110px',
        '124': '124px',
        '125': '125px',
        '129': '129px',
        '160': '160px',
        '180': '180px',
        '208': "208px",
        '212': '212px',
        '220': '220px',
        '250': '250px',
        '278': '278px',
        '318': '318px',
        '331': '331px',
        '340': '340px',
        '362': '362',
        '370': '370px',
        '420': '420px',
        '450': '450px',
        '500': '500px',
      },
      colors: {
        primary: '#000',
        secondary: '#7f7f7f',
        tertiary: '#ff642f',
        hoverPrimary: '#1ca1c1',
        borderPrimary: '#ccd7e6'
      },
      backgroundColor: {
        primary: '#fff',
        secondary: '#ff642b',
        tertiary: '#f9f9f9',
        quaternary: '#8fc1d1',
        drawerPrimary: '#33b6d5',
        drawerSecondary: '#4a4e58',
        hoverPrimary: '#1ca1c1',
        buttonPrimary: '#f4f5f9',
        modalPrimary: '#d7ebf5'
      },
      text: {
        'xs': '12px',
        'sm': '14px',
        'lg': '16px',
        'xl': '17px'
      },
      backgroundImage: {
        'user-item': 'url("assets/images/dashboards/user-icon.svg")',
        'back': 'url("assets/images/dashboards/back-icon.svg")',
        'recipe-item': 'url("assets/images/dashboards/food-icon.svg")',
        'close': 'url("assets/images/dashboards/close-icon.svg")',
        'add-item': 'url("assets/images/dashboards/add-icon.svg")',
        'menu': 'url("assets/images/header/menu.svg")',
        'search': 'url("assets/images/header/search.svg")',
        'avata': 'url("assets/images/header/avata-header.png")',
        'logo': 'url("assets/images/logo/logo.svg")',
        'reply': 'url("assets/images/recipe-details/reply.svg")',
        'favorite': 'url("assets/images/recipe-details/favorite.svg")',
        'serving': 'url("assets/images/recipe-details/icon-edit.svg")',
        'print': 'url("assets/images/recipe-details/print.svg")',
        'star': 'url("assets/images/delicious/star.svg")',
        'dropdown': 'url("assets/images/header/arrow-down.svg")',
        'facebook': 'url("assets/images/footer/facebook.svg")',
        'instagram': 'url("assets/images/footer/instagram.svg")',
        'twitter': 'url("assets/images/footer/twitter.svg")',
        'youtube': 'url("assets/images/footer/youtube.svg")',
        'arrow-right': 'url("assets/images/banner/arrows-right.svg")',
        'create-date': 'url("assets/images/recipe-details/icon-date.svg")',
      }
    },
  },
  plugins: [],
};
